Paas 481
Jahia/paas_jelastic_backup pull request #67
Opened 2020-11-06 17:56 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-481

Short description:

2020-11-06 23:25 UTC, adoux requested changes
I'm sorry I "did my Kevin" but aside from these few changes requested, well done!

2020-11-06 23:25 UTC, adoux commented on mixins/database.yml
> +    # Starting with mariadb 10.4, jahia's db user is not longer root on database
no longer * (sorry I'm gonna act like Kevin for the next lines :see_no_evil:)

2020-11-06 23:25 UTC, adoux commented on mixins/database.yml
> +    # resulting in the need to connect as 'mysql' user and temporaly grants
grant :see_no_evil:

2020-11-06 23:25 UTC, adoux commented on mixins/database.yml
> +    # jahia's db user for is can successfuly import the dump from processing node.
> for is can

:thinking:

2020-11-06 23:25 UTC, adoux commented on mixins/database.yml
> +    # next cmd test if connexion is ok with 'mysql'@'localhost':
tests *

:man_shrugging:

2020-11-09 23:05 UTC, adoux approved these changes

2020-11-09 23:06 UTC, adoux commented
All good to me, I let @laurentfufu review the PR if he wants to, otherwise we can merge

2020-11-10 16:29 UTC, laurentfufu requested changes

2020-11-10 16:29 UTC, laurentfufu commented on mixins/database.yml
> +    - installMariaDBBackup: ${this}
testing if mariabackup is missing before add the repo and try to install it will be welcome here to avoid unnecessary wait during the process

2020-11-12 08:14 UTC, Ronan-Gorain commented on mixins/database.yml
> +    - installMariaDBBackup: ${this}
You're right. 
Done

2020-11-12 12:53 UTC, laurentfufu approved these changes

2020-11-12 12:53 UTC, merged